### PR TITLE
remove sites

### PR DESCRIPTION
**Pull request by matiastucci**
alertasolidaria.com
keepe.rs
tucci.me

---
This change is [Reviewable](https://reviewable.io/reviews/pirate/sites-using-cloudflare/82)

### CODE REVIEW

**Comment by yogeshpadharia** [comment]
remove hdfcbank.com

**Comment by pirate** [comment]
Jesus christ http://www.hdfcbank.com/ is on http, what bank puts their homepage on HTTP?!

**Comment by pirate** [comment]
Confirmed all three sites are static.

**Comment by pirate** [comment]
@yogeshpadharia please submit a separate PR.

**Pull request merged**
