### PR TITLE
removed non-affected sites run by myself

### PR DESCRIPTION
**Pull request by Lego6245**
I run the following sites:

williamsaulnier.com -> Personal portfolio site
enigmasm.com -> Defunct "company" site
loltools.net -> Game tools for LoL and GW2

As primarily static sites that don't collect private user logins or other private info, I don't believe they're affected.

### CODE REVIEW

**Comment by basisbit** [comment]
the leaking also contains information of who browsed your websites, what browser they used and all the other stuff which their webbrowser might have sent in the requests. So technically, these listed websites might have been affected by data leakage, too.

**Comment by Lego6245** [comment]
Interesting. So, any potential client to server request that may have occurred is grounds for inclusion, even if it doesn't contain any sensitive information?

**Comment by basisbit** [comment]
well, that is up to @pirate to decide that.

**Comment by coderobe** [comment]
Any site using CF's reverse-proxy feature is affected because it could potentially have leaked requests to the server.  

If the server does not collect any sensitive or otherwise identifying information, i wouldn't say it's been affected. IPs are not enough, because even if a request source got leaked somewhere, nobody can be sure if the request was actually targeted at that specific site. (Inter-site leakage was supposedly possible)

**Comment by Lego6245** [comment]
Fair enough. Based on @coderobe I stand by my description that all three sites should be removed. The two static sites for obvious reasons, the last because all it does it query a publicly available API with a username (no private, sensitive, or identifying information is collected).

**Comment by pirate** [comment]
@Lego6245 fair enough.  Seems ok to remove by me.

**Comment by Lego6245** [comment]
Thanks so much. Best of luck.

**Pull request merged**
