### PR TITLE
remove sites i own and three sites a person was quite upset about

### PR DESCRIPTION
**Pull request by GusCaplan**

### CODE REVIEW

**Comment by tycoonlover1359** [comment]
Please contact @pirate with info on how to resolve this. #29

**Comment by GusCaplan** [comment]
@pirate i don't have emails on all these domains, but you can verify that i own them on [my keybase](https://keybase.io/snek)

**Comment by pirate** [comment]
@GusCaplan ownership verification is not enough, I need verification that the sites either contain no user data, or did not use the Cloudflare TLS proxy during the affected period.

**Comment by GusCaplan** [comment]
how would you like me to verify that for you

**Pull request closed without merging**
