### PR TITLE
Remove sites not affected

### PR DESCRIPTION
**Pull request by turtledude01**
As I've explained before, My sites are not affected, even though this is true I have warned/reset all passwords of users that were logged in during the affected period of time.

### CODE REVIEW

**Comment by pirate** [comment]
Your site may have been affected.  Sorry man, the whole purpose of this list is to keep an accurate record of all the sites that may have been exposed.
I'm only removing sites that are provably static content, contain no user data, or never used cloudflare during the affected period.

**Comment by turtledude01** [comment]
Are you seriously not listening to what im saying at all? radicaldelta.org - NO USER ACCOUNTS BESIDES MYSELF codywentz.com NOTHING HAS EVEN BEEN ON IT SINCE MID LAST YEAR

**Comment by pirate** [comment]
I'll approve codywentz.com, but the other two aren't static and have logins.

**Comment by turtledude01** [comment]
proof of radicaldelta.org being uninhabited besides myself: http://prntscr.com/ecqexe

**Comment by pirate** [comment]
I can screenshot my bank account with $1,000,000,000,000,000, I know it's frustrating but it's not exactly proof.

**Comment by turtledude01** [comment]
Listen to this: I just took a look through my apache access log and I am recieving multiple invalid and potentially malicious connections to things that are, for example, looking for a phpmyadmin setup file.  Please remove my domains from your list now or I will be forced to find another way to take action as I am reciving too many connections that should not be happening

**Comment by pirate** [comment]
Everyone get dozens of phpmyadmin 404s on domains they host, that's standard procedure for hosting a domain anywhere on the net these days.  Your sites are already indexed by search engines and crawled by all kinds of bots.
If you don't want random junk traffic, add a robots.txt:

https://www.radicaldelta.org/robots.txt
`Disallow: *`

**Comment by turtledude01** [comment]
Please remove all issues that I created and all comments from me.  Thanks

**Comment by pirate** [comment]
@turtledude01 ok removed a bunch of em, although it's kind of pointless because as I said, they're indexed by search engines and archive.org at this point.

**Comment by turtledude01** [comment]
TBH I really don't care anymore, you refuse to remove a website from your list so I want as little trace of it as possible.  Within a few minutes i hope to see my apache logs dropping back to their normal state as they were before... Would still be nice if you were to remove my sites from your repo as there is no foreseeable reason for you to continue storing my domain names.

**Comment by turtledude01** [comment]
Ya know, id actually LOVE to see you or anyone prove that my websites were in fact affected.  I can guarantee you that they weren't ;) 

Also, seems my apache logs returned to normal now.

**Pull request closed without merging**
