### PR TITLE
Added a couple sites I run

### PR DESCRIPTION
**Pull request by hakusaro**
Hiya,

I've issued password resets and the like, but these sites have non-insignificant user accounts so it's worth adding them.

Cheers.

### CODE REVIEW

**Comment by pirate** [comment]
How nice of you, everyone else is angrily trying to get their domains removed!

Mind rebasing? I've made a README change that your commit is reverting currently.

**Comment by coderobe** [comment]
Instead of adding your sites to the "notable sites" list in the readme, i suggest adding them to the actual list instead.  

Oh and it's removing unrelated content from the readme.

**Comment by hakusaro** [comment]
@pirate Yep, gimme a bit. Tried to github web app it, but it's a busy night.

@coderobe good point, didn't see the file.

**Comment by hakusaro** [comment]
Actually, not necessary. Looks like they've been scraped in okay. Cheers!

```
Kurisu 福 ~/Development/sites-using-cloudflare ➤ d55d5f9|master✓
5588 ± : cat sorted_unique_cf.txt | grep tshock.co                                         [18m]
factsthatshock.com
t-shirtshock.com
tshock.co

Kurisu 福 ~/Development/sites-using-cloudflare ➤ d55d5f9|master✓
5589 ± : cat sorted_unique_cf.txt | grep jump.software                                     [18m]
jump.software
```

**Pull request closed without merging**
