### PR TITLE
Remove: OnLoupe.com, GibraltarSoftware.com (used proxy)

### PR DESCRIPTION
**Pull request by kendallmiller**
See https://onloupe.com/blog/cloudflare-vulnerability-does-not-affect-us/, we are not affected by this issue.

### CODE REVIEW

**Comment by pirate** [comment]
Can you fix the conflicts and I'll merge, thanks!

**Comment by coderobe** [comment]
This seems to be cloudflare's general mail that went out to everyone when no data was found. This doesn't mean you were not affected, because your information could've leaked via other sites.

**Comment by coderobe** [comment]
Following what was done with other sites like this, the blog post should be linked in the README but the sites not removed from the list, as sensitive data could've reached the net.

**Comment by pirate** [comment]
@coderobe I've been removing sites that have confirmed they are 100% static, I think it's safe since there's no user data for them to leak.  The blog post linking is for sites that are non-static and used the proxy.

**Comment by coderobe** [comment]
@pirate onloupe does not seem static to me.

**Comment by pirate** [comment]
Hmm, seems like http://gibraltarsoftware.com/ is not static either...

**Comment by pirate** [comment]
After re-reading their blog post @coderobe, these look safe to remove.  Their homepages are indeed static, and the my. domains are self-terminated, so not affected by the leak.

**Comment by coderobe** [comment]
You're right. Closing!

**Comment by pirate** [comment]
Did you mean to merge instead of close?

**Comment by coderobe** [comment]
Right, sorry for that 😳

**Comment by pirate** [comment]
@kendallmiller sorry for the confusion and thanks for your patience as we figured this out, you should be good to go, those domains are no longer on the list.

**Comment by kendallmiller** [comment]
Thanks for your diligence; we did review the data and frankly we're lucky we were slow to get our main app running through Cloudflare so we dodged a much bigger issue.

On Feb 24, 2017, at 6:34 PM, Nick Sweeting <notifications@github.com<mailto:notifications@github.com>> wrote:


@kendallmiller<https://github.com/kendallmiller> sorry for the confusion and thanks for your patience as we figured this out, you should be good to go, those domains are no longer on the list.

**Pull request merged**
