### PR TITLE
Begin the hard work

### PR DESCRIPTION
**Pull request by Xaekai**
Pursuant to #42, trim the list based on server response header criteria

* Removes all domains starting with the numeral 8 from the main list
* Adds a new file of domains starting with the numeral 8 that are confirmed to be using `cloudflare-ngnix`

### CODE REVIEW

**Comment by pirate** [comment]
So the issue with this approach is that we'll inadvertently remove a lot of domains that have turned off cloudflare, but had it on during the affected period.  I'd rather not remove them from the main list, lets make a separate file for confirmed domains and copy them over.

**Comment by Xaekai** [comment]
Site that have proactively disabled Cloudflare have probably already informed their users anyway and don't need to be listed here.

Regardless, that still leaves the issue of managing one giant file.

**Comment by pirate** [comment]
@Xaekai you're right about managing the one giant file, I'll discuss splitting it in IRC.

**Comment by coderobe** [comment]
Splitting by first character sounds like a sane way, that way searching is also gonna be faster.

**Pull request closed without merging**
