### PR TITLE
Remove: frustum.com (static)

### PR DESCRIPTION
**Pull request by tachyonbrush**

### CODE REVIEW

**Comment by tycoonlover1359** [comment]
Hi, I'm on mobile so I cannot see which sites you're talking about. However, your description is blank, so I will assume you do not have proof these sites are unaffected or should otherwise be removed from the list. Please provide proof that they were not subject to CloudBleed or that hey are static sites that do not submit user data. For more information please contact @pirate.

**Comment by coderobe** [comment]
Yeah, please add additional information and proof of ownership. You can send a mail to spam@rob1nn.pw (me) from the affected domains or publish a statement on the site referencing this PR.

**Comment by tachyonbrush** [comment]
Just sent you confirmation email. Thanks

**Comment by coderobe** [comment]
Confirmed, i got a DKIM-signed removal request mail from frustum.com. I am not able to review the diff right now though.

**Comment by tachyonbrush** [comment]
Thanks!!

**Pull request merged**
