### PR TITLE
Update: ZipRecruiter.com (used proxy)

### PR DESCRIPTION
**Pull request by zostay**
We are not impacted by this incident according to them.

Before submitting your pull-request:

 - name of the pull request should be "Add: domain, domain, domain (proxy + DNS)" or "Remove: domain (static), domain (DNS only), domain (static)"
 - do not ask for removal of actually affected websites (any websites using cloudflare reverse proxy)

### HOW TO REMOVE YOUR SITE
1. verify the site is static and contains no user data (I will remove it immediately once I confirm)  

OR  

1. Verify ownership, send me an email from @yourdomain.com, post a random nonce on the domain, or provide keybase proof
2. Verify you did not use the Cloudflare proxy service during the affected period

### CODE REVIEW

**Comment by zostay** [comment]
I sent email to the email address listed on our gh profile just now.

**Comment by coderobe** [comment]
The mail you've got only indicates that no leaked info was found in publicly indexed cached leaks. Your data could've still gotten leaked somewhere.

**Comment by coderobe** [comment]
Please see https://github.com/pirate/sites-using-cloudflare/issues/127#issuecomment-282385955 and https://github.com/pirate/sites-using-cloudflare/issues/87#issuecomment-282372235 for additional information.

**Comment by pirate** [comment]
Closing as you guys are on the `server:cloudflare-nginx` proxy, possibly affected.  You're welcome to submit a PR with a blog post to link to from the README.

**Pull request closed without merging**
