### PR TITLE
Update: betterment.com (no data found in caches)

### PR DESCRIPTION
**Pull request by rynonl**
https://support.betterment.com/customer/portal/articles/2752560-was-my-information-affected-by-the-cloudflare-vulnerability-

### CODE REVIEW

**Comment by coderobe** [comment]
Sounds like a case of [issue #127](https://github.com/pirate/sites-using-cloudflare/issues/127#issuecomment-282385955) and [issue #87](https://github.com/pirate/sites-using-cloudflare/issues/87#issuecomment-282372235)

**Comment by coderobe** [comment]
Also, please put details like the link to the blog post in the PR description. It exists for a reason.

**Comment by pirate** [comment]
Unfortunately the post does not explain whether they have a special setup that didn't proxy traffic or whether they're just repeating statements from Cloudflare's blanket "you were not affected" email.
@rynonl can you confirm whether this is simply a repeat of the email: https://github.com/pirate/sites-using-cloudflare/issues/87#issuecomment-282372235?

**Comment by rynonl** [comment]
ack, didn't realize you weren't trusting the validity of the cloudflare email.  closing this for now.

**Pull request closed without merging**
