### PR TITLE
Update: *.zendesk.com (used proxy)

### PR DESCRIPTION
**Pull request by mashrivastava**
Adding link to Zendesk support article.

### CODE REVIEW

**Comment by youngj** [comment]
Even if a site's data was not found in search engine caches according to CloudFlare's notification, it doesn't mean the site was not affected. Data could have been leaked to other places without CloudFlare having any idea.

**Comment by mashrivastava** [comment]
Hi, The Zendesk instance (`https://instance.zendesk.com`) doesn't use CloudFlare and is not vulnerable to the identified issue. The main Zendesk website (`https://www.zendesk.com`) uses CloudFlare for static images but doesn't host sensitive information.

**Comment by youngj** [comment]
According to https://help.zendesk.com/hc/en-us/articles/115003417127 , Zendesk Chat uses CloudFlare:

> Although Zendesk Chat and our www.zendesk.com site use Cloudflare, we do not utilize the three vulnerable features in our configuration. 

(It's irrelevant whether or not Zendesk uses the three vulnerable features. Data may be leaked from any CloudFlare SSL proxy user regardless of whether they use those features.)

> While initial indications from Cloudflare are that Zendesk was not directly affected by the Cloudflare bug, our security team is continuing to thoroughly investigate the issue as it relates to our systems, integrations and customers. Zendesk takes the security of your data seriously. We will continue to monitor this situation as it develops and will provide more updates as they become available.

Sounds like Zendesk isn't 100% confident that they weren't affected.

**Comment by Zenexer** [comment]
Blocked by #153: the phrase "not affected" is incorrect.  Cloudflare has only determined that several major search engines don't have records of leaks in their caches.  At this time, Cloudflare is not indicating that they have any way of definitively ruling out a leak for any given site, and it remains quite likely that any given high-traffic site were affected.

Cookies were the most frequently found sensitive information in leaks.  This means that if anything.zendesk.com was affected, *.zendesk.com and zendesk.com were also affected.

**Comment by mashrivastava** [comment]
Thanks for the information. We're further investigating this issue with Cloudflare. Closing this request for now.

**Pull request closed without merging**
