### PR TITLE
Add: teespring.com

### PR DESCRIPTION
**Pull request by pirate**
From: https://github.com/pirate/sites-using-cloudflare/pull/138#issuecomment-282459643

### CODE REVIEW

**Comment by Zenexer** [comment]
Do we really want to publish a link to this?  A think a screenshot should be sufficient and is likely to last longer.

**Comment by abalabahaha** [comment]
Linking to DDG is somewhat unreliable, since the results could be scrubbed at any time

**Comment by Dorian** [comment]
@pirate IDK, seems a bit too much to link to leaks in the README no?

**Review by abalabahaha — APPROVED** [review]

**Comment by pirate** [comment]
@ledwards fyi

**Pull request merged**
