### PR TITLE
Update: adafruit.com (used proxy)

### PR DESCRIPTION
**Pull request by CupNoodles**
Confirmation from Cloudflare's support staff that we're unaffected - text redacted and attached below. Thank you for all your quick work pertaining to this issue! 

================

Hi,

Thanks for contacting Cloudflare Customer Support. We have notified all the customers the were affected by the memory leak and I can confirm the zones on your account were not one of them.

Please let us know if you have any other questions.

Kind Regards,

 - Senior Support Engineer

### CODE REVIEW

**Comment by pirate** [comment]
@CupNoodles see https://github.com/pirate/sites-using-cloudflare/pull/114#issuecomment-282370425
We need more than the cloudflare email for confirmation, right now we're only removing sites that did not use the proxy service at all.

If you want, submit a PR with a link to an adafruit post explaining you were likely unaffected, and we can add the note to the readme.
e.g.

- adafruit.com \[no evidence of data leaked](https://adafruit.com/blog/cloudflare-leak-post)

**Comment by coderobe** [comment]
This does sound like a case where CF did actually dig into the data and found that the site was not going through affected proxy nodes. Will need more confirmation on that though.

**Comment by coderobe** [comment]
I am going to close this, because it seems like this site was using the proxy the whole time **and** is serving a log-in page.

**Comment by CupNoodles** [comment]
Hi folks, 

we've posted publicly about leak and why we believe that we were not affected here https://blog.adafruit.com/2017/02/27/cloudflare-states-adafruit-not-part-of-the-cloudflare-issues-cloudbleed-adafruit/ 

If you'd be willing to re-consider our PR in this regard, it would be greatly appreciated. The fact that we *were* using the proxy remains though, so if that's the sole criteria for removal from the list at the moment, then that's valid and understood.

**Comment by pirate** [comment]
@CupNoodles thanks for the proactive blog post! I saw it linked somewhere online earlier today, you're welcome to edit the PR with [official response].  If you want adafruit.com fully removed, can you email them and ask if they mean:

"not affected by the memory leak" == "no evidence of leaked data has been found online"
or if they mean
"not affected by the memory leak" == "never proxied through any of the machines sharing memory space with the bug"?

We can remove you fully if it's the second one.

**Comment by pirate** [comment]
Closing due to inactivity.  This list is rapidly becoming defunct, but if you still want to link something @CupNoodles feel free to re-open with the merge conflict fixed.

**Pull request closed without merging**
