### PR TITLE
Remove: phin-cdn.stream, phineas.io (static)

### PR DESCRIPTION
**Pull request by Phineas**
https://phineas.io
https://phin-cdn.stream

https://keybase.io/phineas

### CODE REVIEW

**Comment by coderobe** [comment]
phin-cdn.stream looks like a non-static website that goes through the cf proxy

**Comment by pirate** [comment]
+1

**Comment by Phineas** [comment]
@coderobe It is static, it's just a cdn server hosting on a GCloud instance which serves images/css files

**Comment by coderobe** [comment]
I see

**Pull request merged**
