### PR TITLE
Removed domains that use only Clouflare DNS service

### PR DESCRIPTION
**Pull request by don-mums**
Removed domains:
jahn.sk
mums.cz
erly.cz
smrdim.cz
skra.cz
damefotku.cz
czech-diaspora.xyz
twisto.cz
twistopay.cz

### CODE REVIEW

**Comment by tycoonlover1359** [comment]
Please prove that these sites are unaffected by CloudBleed. Fur further information please contact @pirate

**Comment by don-mums** [comment]
Are IP addresses served by DNS strong enough? None of those domains use CF edge servers.

**Comment by tycoonlover1359** [comment]
I'm not sure of this. I'm only assisting Pirate with things I can help with, like answering issues and making PRs as necessary. Like I said, contact @pirate for more. Sorry!

**Comment by don-mums** [comment]
I wrote him an e-mail because I'm not sure what he wants as the proof.

**Comment by don-mums** [comment]
Too much effort, too little gain. Closing pull request.

**Comment by pirate** [comment]
I've confirmed that your sites are static or don't use cloudflare termination, I got the email verification as well.

**Comment by pirate** [comment]
If you want to fix the conflicts and re-submit, I'd be happy to merge your PR.

**Comment by pirate** [comment]
Thanks for you patience @don-mums! merged.

**Pull request merged**
