### PR TITLE
Remove: account.leagueoflegends.com

### PR DESCRIPTION
**Pull request by markofu**
Remove: account.leagueoflegends.com -> confirmation sent via email.

### CODE REVIEW

**Comment by Phineas** [comment]
@markofu This domain was & still is using the proxy service.

**Comment by Phineas** [comment]
Never mind, received the email - removing the domain. Thank you!

**Comment by markofu** [comment]
Thanks @Phineas 👍

**Comment by tonyztan** [comment]
@Phineas @pirate Have we changed the policy? Why is a website currently using the proxy being removed?

**Comment by Phineas** [comment]
@tonyztan They got an email specifically from Cloudflare saying their domain wasn't affected, I was forwarded it.

**Comment by tonyztan** [comment]
@Phineas Would this be a similar situation to #154 and #153, where there is "no evidence of compromised data", meaning "no leaked data found in several search engine caches", but also no positive evidence that definitely no data was leaked from the site at any point?

**Comment by Phineas** [comment]
@tonyztan Cloudflare specifically said in the email that their site was not affected in any way.

**Comment by tonyztan** [comment]
@Phineas I see. Thanks!

**Comment by tonyztan** [comment]
@Phineas @coderobe Sorry to bring this up again, but would [the comment from pull #210](https://github.com/pirate/sites-using-cloudflare/pull/210#issuecomment-282752664) have anything to do with this? As in, ["we're not trusting cloudflare's 'you were not affected' emails"](https://github.com/pirate/sites-using-cloudflare/issues/87#issuecomment-282372235), and ["Anything that routes through Cloudflare could have possibly leaked data via third partys that caused the leak to occur."](https://github.com/pirate/sites-using-cloudflare/issues/127#issuecomment-282385955)

**Comment by coderobe** [comment]
I don't know why this PR was merged. It should not have been IMO.

**Comment by abalabahaha** [comment]
The way Phineas worded his comment sounded like Cloudflare had responded personally to a support email, but the email subject in the screenshot he posted looks like the misleading blanket email Cloudflare sent...

**Comment by coderobe** [comment]
That's what it sounds like, yeah. CC @Phineas

**Comment by pirate** [comment]
@Phineas or @markofu can one of you forward me the Cloudflare email to LoLcloudflare@sweeting.me?  If it was the blanket "your data wasn't found in caches" email, then I'd like to revert this PR asap, there's a lot of questioning going around the League of Legends forums and it would be nice to clear it up.  It would also be great to link to an official LoL Cloudbleed response blog post, although afaik they haven't published one yet.

**Comment by markofu** [comment]
@pirate Hey, which questions are you referring to? 

I work in Security at Riot (google me, if you want proof more proof, let me know). Regarding official word, we officially posted on LoL Subreddit last Friday evening. We may still post to the Forums but I'm doubtful on that. We have answered players' questions and concerns via the Subreddit and through our Player Support system.

We have had several calls with Cloudflare and I've forwarded you on a private email to us (at Riot).

If you still want to revert the PR, that's your call and I defer to your judgement on it.

**Pull request merged**
