### PR TITLE
Remove subinsb.com

### PR DESCRIPTION
**Pull request by subins2000**
My blog does not have any user data. It's just a WordPress blog with no user signups. It's just for reading posts.

See for yourself : [https://subinsb.com](https://subinsb.com)

### CODE REVIEW

**Comment by pirate** [comment]
I like your bash Christmas tree :)

Unfortunately it's hard to confirm that you don't have any users signing up, as a screenshot is not enough proof.  So far I'm only removing sites that are static, have no logins at all, or don't use cloudflare.

**Comment by turtledude01** [comment]
@subins2000 I was tempted to tell you as soon as I saw your request that it wouldn't be accepted... I've been trying to get my sites off it with no luck for over 4 hours.  I personally believe if a website can prove ownership, and requests to be removed then it SHOULD be removed as I personally do not want ANY extra trafic to my sites.

**Comment by turtledude01** [comment]
Gl with @pirate accepting that once again @subins2000 ... I have a site that literally only has me as a user and he refuses to remove it

**Comment by pirate** [comment]
As I stated earlier the criteria for removal:

I'm only removing sites that are provably static content (e.g. github pages), contain **no** user data, or never used cloudflare during the affected period.
For domain verification I need either a DKIM signed email from the domain, a keybase verification, or a file uploaded with a random number that I'll give you.

**Pull request closed without merging**
